import { Platform, StyleSheet } from 'react-native';

const authStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0F0C29',
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    justifyContent: 'center',
  },
  gradientFill: {
    ...StyleSheet.absoluteFillObject,
  },
  bgBlobTop: {
    position: 'absolute',
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: 'rgba(255, 68, 120, 0.24)',
    top: -110,
    right: -120,
  },
  bgBlobBottom: {
    position: 'absolute',
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: 'rgba(245, 158, 11, 0.22)',
    bottom: -130,
    left: -110,
  },
  bgBlobMiddle: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    top: '24%',
    left: -100,
  },
  bgBlobRightSoft: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    top: '52%',
    right: -100,
  },
  bgBlobBlue: {
    position: 'absolute',
    width: 290,
    height: 290,
    borderRadius: 145,
    backgroundColor: 'rgba(56, 189, 248, 0.18)',
    top: '45%',
    left: '36%',
  },
  meshBandTop: {
    position: 'absolute',
    top: 90,
    left: -30,
    right: -30,
    height: 110,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.05)',
    transform: [{ rotate: '-9deg' }],
  },
  meshBandBottom: {
    position: 'absolute',
    bottom: 70,
    left: -35,
    right: -35,
    height: 100,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.04)',
    transform: [{ rotate: '7deg' }],
  },
  dot: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#F8F7FF',
  },
  dotTopRight: {
    top: 170,
    right: 38,
  },
  dotMiddleLeft: {
    top: '52%',
    left: 34,
  },
  dotBottomRight: {
    bottom: 155,
    right: 44,
  },
  authBody: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
  },
  brandHeader: {
    alignItems: 'center',
    marginBottom: 22,
  },
  logoCircle: {
    width: 94,
    height: 94,
    borderRadius: 47,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    marginBottom: 12,
  },
  logoPaw: {
    fontSize: 42,
  },
  brandTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: '#F0EEFF',
  },
  brandTagline: {
    marginTop: 4,
    fontSize: 15,
    color: '#9490A8',
  },
  card: {
    width: '100%',
    backgroundColor: 'rgba(20,20,40,0.88)',
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.5,
    shadowRadius: 24,
    elevation: 14,
  },
  cardTitle: {
    fontSize: 27,
    fontWeight: '800',
    color: '#F0EEFF',
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#C4C0D8',
    marginBottom: 8,
    marginTop: 10,
  },
  passwordHeaderRow: {
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputRow: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  inputRowFocused: {
    borderColor: '#8B5CF6',
    backgroundColor: 'rgba(139,92,246,0.1)',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.26,
    shadowRadius: 10,
    elevation: 2,
  },
  inputRowError: {
    borderColor: '#EF4444',
    backgroundColor: 'rgba(127, 29, 29, 0.35)',
  },
  leftIcon: {
    fontSize: 17,
    marginRight: 8,
    color: '#C4C0D8',
  },
  textInput: {
    flex: 1,
    color: '#F0EEFF',
    fontSize: 15,
    paddingVertical: 10,
    ...(Platform.OS === 'web' && {
      outlineStyle: 'none',
    }),
  },
  eyeIcon: {
    fontSize: 18,
    paddingLeft: 8,
    color: '#C4C0D8',
  },
  errorText: {
    color: '#FCA5A5',
    fontSize: 12,
    marginTop: 6,
    fontWeight: '600',
  },
  linkOrange: {
    color: '#9B7DFF',
    fontSize: 13,
    fontWeight: '700',
  },
  primaryButton: {
    marginTop: 18,
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: '#7C3AED',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6D28D9',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.48,
    shadowRadius: 22,
    elevation: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  dividerRow: {
    marginVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  dividerText: {
    marginHorizontal: 10,
    color: '#9490A8',
    fontSize: 12,
    fontWeight: '500',
  },
  googleButton: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleG: {
    color: '#DB4437',
    fontSize: 19,
    fontWeight: '700',
    marginRight: 8,
  },
  googleLabel: {
    color: '#F0EEFF',
    fontSize: 15,
    fontWeight: '600',
  },
  footerRow: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerText: {
    color: '#9490A8',
    fontSize: 14,
  },
  footerLink: {
    color: '#9B7DFF',
    fontSize: 14,
    fontWeight: '700',
  },
  simpleText: {
    color: '#C4C0D8',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 10,
  },
  todoNote: {
    color: '#A78BFA',
    fontSize: 13,
    marginBottom: 8,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  half: {
    flex: 1,
  },
  stepDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 8,
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.24)',
  },
  stepDotActive: {
    width: 20,
    borderRadius: 5,
    backgroundColor: '#8B5CF6',
  },
  strengthRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    marginBottom: 4,
  },
  strengthBar: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  strengthWeak: {
    backgroundColor: '#EF4444',
  },
  strengthFair: {
    backgroundColor: '#F59E0B',
  },
  strengthGood: {
    backgroundColor: '#22C55E',
  },
  strengthStrong: {
    backgroundColor: '#06B6D4',
  },
  strengthText: {
    fontSize: 12,
    color: '#9490A8',
    marginTop: 2,
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: '#8B5CF6',
    borderColor: '#8B5CF6',
  },
  checkMark: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  termsText: {
    flex: 1,
    color: '#C4C0D8',
    fontSize: 13,
  },
});

export default authStyles;
